- name: orinnano_playbook
  hosts: iris_hosts
  tasks:
        - name: built in ping
          ansible.builtin.ping:

        - name: print hello world
          ansible.builtin.debug:
            msg: hello orin
