name: Orin nx remote updates

on:
  push

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY_ORIN }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.IRIS1 }} >> ~/.ssh/known_hosts
        ssh-keyscan -t rsa ${{ secrets.IRIS2 }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        # Debug: Check the content of id_rsa and known_hosts
        ls -l ~/.ssh
        cat ~/.ssh/known_hosts
      shell: bash

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible
      shell: bash

    - name: Run Ansible playbook
      run: |
        cd ansible
        ansible-playbook -i iris_inventory.ini iris_playbook.yaml
      shell: bash
      env:
        JETSON_USER: ${{ secrets.ansible_user }}
        IRIS1: ${{ secrets.IRIS1 }}
        IRIS2: ${{ secrets.IRIS2 }}
