name: Orin nx remote updates

on: 
  push

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v4

    - name: ssh on jetson
      run: | 
        mkdir ~/.ssh
        echo "${{secrets.SSH_KEY_ORIN}}" >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        less ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{secrets.IRIS1}} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
      shell:  bash

    - name:  ansible installation
      run: | 
            sudo apt update
            sudo apt install -y ansible


    - name:  Run ansible playbook
      run:  |
              cd ansible 
              ansible-playbook -i iris_inventory.ini iris_playbook.yaml
      shell: bash
            
