name: Orin nx remote updates

on: 
  push

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v4

    - name: ssh on jetson
      run: | 
        mkdir ~/.ssh
        echo "${{secrets.SSH_KEY_ORIN}}" >> ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      shell:  bash

    - name:  ansible installation
      run: | 
            apt update
            apt install -y ansible


    - name:  Run ansible playbook
      run:  |
              pwd
      shell: bash
            
