name: ros2 Publisher Action Demo

on: 
  push

jobs:
  Publisher-ros2:
    runs-on: ubuntu-latest
    container: 
      image: ros:humble

    steps:
      - name: copy github repo locally
        uses: actions/checkout@v4

      - name: ros2 setup
        run: | 
              source /opt/ros/humble/setup.bash
              cd /__w/pubsub_action/pubsub_action
              colcon build --packages-select py_pubsub
        shell: bash

      # - name: run Publisher
      #   run:  |
      #         source /opt/ros/humble/setup.bash
      #         # pwd && ls -a
      #         source /__w/pubsub_action/pubsub_action/install/setup.bash
      #         cd /__w/pubsub_action/pubsub_action
      #         # ros2 run py_pubsub talker
        # shell: bash
        
      - name: creating a package - zip if prev succeeds
        if:   ${{success()}}
        run:  | 
                apt install zip
                cd /__w/pubsub_action
                zip -r pubsub_action.zip .
                ls -a
        shell: bash

      # - name: upload packages
      #   if:  ${{success()}}
      #   run:  
