name: ros2 Publisher Action Demo

on: 
  push

jobs:
  Publisher-ros2:
    runs-on: ubuntu-latest
    container: 
      image: ros:humble
    permissions:
      contents: write 

    steps:
      - name: Copy GitHub repo locally
        uses: actions/checkout@v4

      - name: ROS2 and version setup
        run: | 
              source /opt/ros/humble/setup.bash
              cd /__w/pubsub_action/pubsub_action
              colcon build --packages-select py_pubsub
              echo "TAG_NAME=${{ github.event.release.tag_name }}"
              echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        shell: bash

      # - name: Run Publisher
      #   run:  |
      #         source /opt/ros/humble/setup.bash
      #         source /__w/pubsub_action/pubsub_action/install/setup.bash
      #         cd /__w/pubsub_action/pubsub_action
      #         ros2 run py_pubsub talker
      #   shell: bash
        
      - name: Creating a package - .zip
        if: ${{ success() }}
        run: | 
              apt update
              apt install -y zip dpkg-dev python3-bloom python3-rosdep fakeroot debhelper dh-python
              rm /etc/ros/rosdep/sources.list.d/20-default.list        
              rosdep init
              rosdep update -y
              cd /__w/pubsub_action
              zip -r pubsub_action_${version}.zip .
              

      - name: Creating a package -  .deb
        if: ${{ success() }}
        run: | 
              cd /__w/pubsub_action/pubsub_action/src/py_pubsub
              bloom-generate rosdebian
              fakeroot debian/rules binary
              pwd
              cd ..
              mv ros-humble-py-pubsub*.deb ros-humble-py-pubsub_${version}-0jammy_amd64.deb
              ls -a
              
        shell: bash

      - name: Create release - for package
        if: ${{ success() }}
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # skipIfReleaseExists: True
          # allowUpdates: false
          tag_name: ${{ github.ref_name }} 
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload packages - release
        if: ${{ success() }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /__w/pubsub_action/pubsub_action/src/ros-humble-py-pubsub_${{ env.VERSION }}-0jammy_amd64.deb
          asset_name: ros-humble-py-pubsub_${{ env.VERSION }}-0jammy_amd64.deb
          asset_content_type: application/x-deb

      - name: Upload .zip package - release
        if: ${{ success() }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /__w/pubsub_action/pubsub_action_${version}.zip
          asset_name: pubsub_action_${version}.zip
          asset_content_type: application/zip
